### ISSUE TITLE
结构体里的标量指针字段还是展示地址

### ISSUE THREAD

**Issue by hawayiii** [mix-go/xfmt#3]
func TestPrint(t *testing.T) {
	type tt1 struct {
		D int
		E *float64
	}
	type tt struct {
		A int
		B string
		C *tt1
	}

	var tmp tt
	_ = faker.FakeData(&tmp)

	res := xfmt.Sprintf("%+v", tmp)
	t.Log(res)
}

输出：{A:43 B:rvRvsMjsgUZLiFLinZYakiCcb C:0xc0048c9400:&{D:63 E:0xc0048fb4e8:0xc0048fb4e8}}
结构体里的float64指针字段还是展示了地址。

问题应该是出现在这里，为啥用了地址，应该是用Interface，最后用interface来printf
<img width="721" alt="image" src="https://github.com/mix-go/xfmt/assets/23328070/97cb331d-0fe7-4361-b822-3af89b5a70a9">

**Comment by onanying** [comment]
没有考虑到 int,float,string 这种标量是指针的场景
